---
- name: Install Nginx on Ubuntu
  hosts: ec2_instances  # Replace with your target hosts or group
  become: yes                # Use sudo to install packages
  tasks:
    - name: Update apt repository
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Ensure Nginx is started and enabled
      systemd:
        name: nginx
        state: started
        enabled: yes